"use client";
import { useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight } from 'lucide-react';
import { plans } from '@/data/pricing';
import { services } from '@/data/services';
import { site } from '@/data/site';
import { contactSchema } from '@/lib/contact';
export function ContactForm({ initialInterest, enabled }: { initialInterest: string; enabled: boolean }) { const [status, setStatus] = useState(''); const [failed, setFailed] = useState(false); const [pending, setPending] = useState(false); const [sent, setSent] = useState(false);
 async function submit(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = event.currentTarget; const values = new FormData(form); const result = contactSchema.safeParse({ ...Object.fromEntries(values), consent: values.get('consent') === 'on' }); if (!result.success) { setFailed(true); setStatus(result.error.issues[0].message); return; } if (!enabled) { const { name, email, business, interest, message } = result.data; const body = `Name: ${name}\nEmail: ${email}\nBusiness: ${business}\nInterest: ${interest}\n\n${message}`; window.location.href = `mailto:${site.email}?subject=${encodeURIComponent(`${interest} — ${business}`)}&body=${encodeURIComponent(body)}`; setFailed(false); setStatus('Your email draft is ready in your email app. Please send it there to complete your enquiry. Nothing has been submitted by this website.'); return; }
 setPending(true); setStatus(''); setFailed(false); try { const response = await fetch('/api/contact', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(result.data) }); const data = await response.json(); if (!response.ok) throw new Error(data.error || 'We couldn’t send your enquiry. Please try email.'); setSent(true); setStatus('Your enquiry has been sent. Thank you for telling us about your business.'); form.reset(); } catch (error) { setFailed(true); setStatus(error instanceof Error ? error.message : 'Something went wrong. Please email us directly.'); } finally { setPending(false); } }
 return <form className="contact-form" onSubmit={submit}><h2>Tell us about your next chapter.</h2><p>{enabled ? 'A few details will help us start the right conversation.' : 'Fill in your details to prepare an email. Your email app opens when you continue; send the draft there.'}</p><div className="form-grid"><div className="field"><label htmlFor="name">Your name *</label><input id="name" name="name" autoComplete="name" placeholder="Your name" required minLength={2} maxLength={100}/></div><div className="field"><label htmlFor="email">Email address *</label><input id="email" name="email" type="email" autoComplete="email" placeholder="you@yourbusiness.com" required maxLength={254}/></div></div><div className="field"><label htmlFor="business">Business name *</label><input id="business" name="business" autoComplete="organization" placeholder="The business you’re building" required minLength={2} maxLength={160}/></div><div className="field"><label htmlFor="interest">How can we help? *</label><select id="interest" name="interest" defaultValue={initialInterest}><option>Free brand audit</option><optgroup label="Growth packages">{plans.map(plan => <option key={plan.name}>{plan.name}</option>)}</optgroup><optgroup label="Services">{services.map(service => <option key={service.slug}>{service.title}</option>)}</optgroup></select></div><div className="field"><label htmlFor="message">What would you like to grow? *</label><textarea id="message" name="message" placeholder="Tell us what you do, where you’re based and your biggest goal." required minLength={20} maxLength={3000}/></div><div className="honeypot" aria-hidden="true"><label htmlFor="website">Leave this field empty</label><input id="website" name="website" tabIndex={-1} autoComplete="off"/></div><label className="consent"><input type="checkbox" name="consent" required/><span>I agree to be contacted about this enquiry. Read our <Link href="/privacy">privacy policy</Link>.</span></label><button className="button button-primary" disabled={pending || sent} type="submit">{pending ? 'Sending…' : sent ? 'Enquiry sent' : enabled ? 'Let’s talk growth' : 'Prepare my email'}<ArrowUpRight size={18} aria-hidden="true"/></button>{status && <div className={`form-status ${failed ? 'error' : ''}`} role={failed ? 'alert' : 'status'}>{status}</div>}<p className="email-fallback">Prefer to email? <a href={`mailto:${site.email}`}>{site.email}</a></p></form>;
}
