import Link from 'next/link';
import { ArrowUpRight, ArrowRight, Check } from 'lucide-react';
import type { ReactNode } from 'react';
import { site, processSteps, faqs } from '@/data/site';
import { plans, formatPrice, pricingNote } from '@/data/pricing';
export function ButtonLink({ href = '/contact', children, secondary = false, className = '' }: { href?: string; children: ReactNode; secondary?: boolean; className?: string }) { return <Link href={href} className={`button ${secondary ? 'button-secondary' : 'button-primary'} ${className}`}>{children}<ArrowUpRight size={18} aria-hidden="true" /></Link>; }
export function SectionHeading({ eyebrow, title, description, light = false }: { eyebrow: string; title: ReactNode; description?: string; light?: boolean }) { return <div className={`section-heading ${light ? 'light' : ''}`}><span className="eyebrow"><span />{eyebrow}</span><h2>{title}</h2>{description && <p>{description}</p>}</div>; }
export function PageHero({ eyebrow, title, description, children }: { eyebrow: string; title: ReactNode; description: string; children?: ReactNode }) { return <section className="page-hero dark"><div className="container"><span className="eyebrow"><span />{eyebrow}</span><h1>{title}</h1><p>{description}</p>{children}</div><div className="hero-orbit" aria-hidden="true" /></section>; }
export function CTA() { return <section className="section cta-section"><div className="container cta-panel dark"><div><span className="eyebrow"><span />Your next chapter starts here</span><h2>Big plans for your business?<br /><span className="gradient-text">Let’s make the next move.</span></h2><p>{site.auditDescription}</p><ButtonLink>{site.audit}</ButtonLink></div><div className="cta-symbol" aria-hidden="true"><ArrowUpRight strokeWidth={1} /></div></div></section>; }
export function Process() { return <section className="section process dark"><div className="container"><SectionHeading light eyebrow="A little clarity. A lot of possibility." title={<>Good growth starts<br />with a good plan.</>} /><div className="process-grid">{processSteps.map((step, i) => <article key={step.title}><div className="step-top"><span className="step-number">0{i + 1}</span>{i < 2 && <ArrowRight aria-hidden="true" />}</div><h3>{step.title}</h3><p>{step.description}</p></article>)}</div></div></section>; }
export function PricingCards() { return <><div className="pricing-grid">{plans.map(plan => <article className={`price-card ${plan.popular ? 'popular' : ''}`} key={plan.name}>{plan.popular && <div className="popular-label"><span />Most popular</div>}<span className="plan-name">{plan.name}</span><p>{plan.description}</p><div className="price">{formatPrice(plan.price)}<span>/ month</span></div><ButtonLink href={`/contact?plan=${encodeURIComponent(plan.name)}`} secondary={!plan.popular}>Choose {plan.name.split(' ')[0]}</ButtonLink><div className="price-divider" /><ul className="check-list">{plan.features.map(feature => <li key={feature}><Check size={17} aria-hidden="true" />{feature}</li>)}</ul></article>)}</div><p className="pricing-note">{pricingNote}</p></>; }
export function FAQ() { return <section className="section"><div className="container faq-layout"><SectionHeading eyebrow="A few things you might be wondering" title={<>Good questions.<br />Straight answers.</>} /><div className="faq-list">{faqs.map(faq => <details key={faq.question}><summary>{faq.question}<span aria-hidden="true">+</span></summary><p>{faq.answer}</p></details>)}</div></div></section>; }
