import Link from 'next/link';
import { notFound } from 'next/navigation';
import { Check } from 'lucide-react';
import { PageHero, CTA, ButtonLink } from '@/components/ui';
import { caseStudies, caseStudyDisclosure } from '@/data/case-studies';
import { pageMetadata } from '@/lib/seo';
export const dynamicParams = false;
export function generateStaticParams() { return caseStudies.map(s => ({ slug: s.slug })); }
export async function generateMetadata({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const study = caseStudies.find(s => s.slug === slug); return study ? pageMetadata(`${study.name}: Growth Plan`, study.summary, `/case-studies/${slug}`) : {}; }
export default async function CaseDetail({ params }: { params: Promise<{ slug: string }> }) { const { slug } = await params; const study = caseStudies.find(s => s.slug === slug); if (!study) notFound(); return <><PageHero eyebrow={`${study.category} · ${study.location} · Illustrative plan`} title={study.name} description={study.headline}><nav className="breadcrumb" aria-label="Breadcrumb"><Link href="/case-studies">Case studies</Link><span aria-hidden="true">/</span><span>{study.name}</span></nav></PageHero><section className="section"><div className="container"><p className="disclosure">{caseStudyDisclosure}</p><div className="detail-layout"><div><h2>The starting point</h2><p>{study.baseline}</p><h2>The growth plan</h2><div className="timeline">{study.phases.map(phase => <article key={phase.title}><span className="tiny-label">{phase.time}</span><h3>{phase.title}</h3><p>{phase.description}</p></article>)}</div></div><aside className="detail-panel"><h2>The challenge</h2><ul className="check-list">{study.challenge.map(item => <li key={item}><Check size={17} aria-hidden="true"/>{item}</li>)}</ul><h2>The takeaway</h2><p>{study.takeaway}</p><ButtonLink>Build a plan for my business</ButtonLink></aside></div><div className="metric-grid">{study.targets.map(target => <div key={target.label}><strong>{target.value}</strong><span>{target.label}</span></div>)}</div><p className="disclosure">These are planning targets from the supplied workbook, not reported results. Actual outcomes depend on the business, market, budget and execution.</p></div></section><CTA/></>; }
